version: 2
jobs:
    checkout-and-cache-dependencies:
        working_directory: ~/cz-ls-commits
        docker:
            - image: circleci/node:12.18.4
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - dependency-cache-{{ checksum "yarn.lock" }}
            - run: yarn
            - save_cache:
                  key: dependency-cache-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn

    release:
        working_directory: ~/cz-ls-commits
        docker:
            - image: circleci/node:12.18.4
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - dependency-cache-{{ checksum "yarn.lock" }}
            - run: yarn
            - run: yarn semantic-release

workflows:
    version: 2
    checkout-and-release:
        jobs:
            - checkout-and-cache-dependencies
            - release:
                  filters:
                      branches:
                          only:
                              - master
