on: push
name: Find Secrets
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Secret Scan
              id: Truffle-Hog
              uses: JiDevOps/secret-scan@872c0fdaefd12020f2324c42be4512438f1ff64e
              with:
                exclude_path: './exclude_paths.txt'
